pull_request_rules:
  - name: automatic merge when CI passes
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {}