language: scala

sudo: false

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.18
    - TRAVIS_SBT_VERSION=1.2.8

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ^^$TRAVIS_SBT_VERSION scripted

