language: scala

sudo: false

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.18
    - TRAVIS_SBT_VERSION=1.0.0

jdk:
  - oraclejdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ^^$TRAVIS_SBT_VERSION scripted

matrix:
  exclude:
    - jdk: openjdk7
      env: TRAVIS_SBT_VERSION=1.0.0
