language: scala

sudo: false

scala:
  - 2.10.6

jdk:
  - oraclejdk8
  - openjdk7

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt ++$TRAVIS_SCALA_VERSION scripted

branches:
  only:
    - master
